version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    image: php:7.4-apache
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: rolcontrol
      MYSQL_USER: ec2-user
      MYSQL_PASSWORD: toor
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ec2-user
      PMA_PASSWORD: toor
      PMA_PORT: 3306
    ports:
      - 8080:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 