FROM php:7.4-apache

# Instala extensiones necesarias para conectar a MySQL
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Instala sendmail
RUN apt-get update && apt-get install -y sendmail
RUN echo "hostname" > /etc/mail/local-host-names

# Reinicia el servicio sendmail
RUN service sendmail restart
