version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=rolcontrol
      - MYSQL_USER=ec2-user
      - MYSQL_PASSWORD=toor
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=ec2-user
      - PMA_PASSWORD=toor
    ports:
      - 8080:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge