version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    image: php:7.4-apache
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    restart: always

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=toor
    networks:
      - app-network
    restart: always

networks:
  app-network:

volumes:
  db_data: